### ISSUE TITLE
Installing on i686-m64

### ISSUE THREAD

**Issue by raosvikram** [njsmith/pysrilm#2]
I had to add compiler and linker arguments in setup.py.

``` python
setup(
    cmdclass = {'build_ext': build_ext},
    ext_modules = [
      Extension("srilm",
                ["srilm.pyx"],
                language="c++",
                include_dirs=[SRILM_INCLUDE_DIR],
                libraries=["oolm", "dstruct", "misc"],
                extra_compile_args=['-fopenmp'],
                extra_link_args=["-L" + SRILM_LIB_DIR, '-lgomp', '-lz'],
                )
      ],
)
```

The install worked fine even otherwise, but on importing it complained that it couldn't find "gzvprintf" and something else about GOMP.

**Comment by njsmith** [comment]
should be fixed by the pull request I just merged. I think github never notified me of this bug report? sorry about that.
