### ISSUE TITLE
Problem to Install pysrilm on Windows 

### ISSUE THREAD

**Issue by strnam** [njsmith/pysrilm#7]
I try to install pysrilm on windows. I have builded SRILM on windows by cygwin64
I edited setup.py accord donglixp: 
extra_link_args=["-L" + SRILM_LIB_DIR, "-liconv"],

My command on  Cygwin64 Terminal:
python setup.py install build --compiler=mingw32

But i receive this error:
...
running install
running build
running build_ext
skipping 'srilm.cpp' Cython extension (up-to-date)
building 'srilm' extension
C:\cygwin64\bin\gcc.exe -mno-cygwin -mdll -O -Wall -IC:\cygwin64\srilm\include -IC:\Python27\include -IC:\Python27\PC -c srilm.cpp -o build\temp.win-amd64-2.7\Release\srilm.o -fopenmp
gcc: error: unrecognized command line option ‘-mno-cygwin’
error: command 'C:\cygwin64\bin\gcc.exe' failed with exit status 1

anyone have idea to solve?
Thank

**Comment by njsmith** [comment]
Is your python itself compiled using cygwin? (If you're not sure, then check whether the Python variable `sys.platform` is `"cygwin"`.)

If your Python _is_ compiled using cygwin, then I dunno, I guess this is a bug in distutils, and I don't use windows or cygwin myself so I can't really help you beyond that :-/. Whoever built your python might have some suggestions.

If your Python is _not_ compiled using cygwin, then this has no hope of working -- you can't mix cygwin and non-cygwin code. You need to use a mingw-w64 gcc to compile srilm and pysrilm, not cygwin gcc. I'd suggest trying Carl Kleffner's mingw-w64 builds and see if that helps: https://bitbucket.org/carlkl/mingw-w64-for-python/downloads
(They're also included with WinPython.)

**Comment by strnam** [comment]
My sys.platform is 'win32'. I don't have many knowledge about cygwin =( 
I compiled srilm by cygwin according some tutorial. I'm trying recompile it by mingw-w64
Thank you very much.

**Comment by njsmith** [comment]
Good luck!
